#!/usr/bin/env bash

if [ -n "$IN_NIX_TERMUX_PROOT" ]; then
  exec "~/.nix-profile/bin/$(basename "$0")" "$@"
else
  exec "$(dirname "$(readlink -f "$0")")/start" "$HOME/.nix-profile/bin/$(basename "$0")" "$@"
fi
